const API_ERROR_CODES = {
    DUPLICATE_ORDER: 'DUPLICATE_ORDER',
    INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
    ORDER_EDIT_LOCKED: 'ORDER_EDIT_LOCKED',
    MATERIAL_NOT_FOUND: 'MATERIAL_NOT_FOUND',
    RECEIVED_QUANTITY_EXCEEDED: 'RECEIVED_QUANTITY_EXCEEDED',
    MATERIAL_ID_REQUIRED: 'MATERIAL_ID_REQUIRED',
    INVALID_RECEIPT_QUANTITY: 'INVALID_RECEIPT_QUANTITY',
    ORDER_ITEMS_REQUIRED: 'ORDER_ITEMS_REQUIRED',
    ORDER_ITEM_ID_REQUIRED: 'ORDER_ITEM_ID_REQUIRED',
    RECEIPT_ITEM_KEY_REQUIRED: 'RECEIPT_ITEM_KEY_REQUIRED',
    DUPLICATE_RECEIPT_ITEM: 'DUPLICATE_RECEIPT_ITEM',
    ORDER_ITEM_NOT_FOUND: 'ORDER_ITEM_NOT_FOUND',
    ORDER_ITEM_KEY_MISMATCH: 'ORDER_ITEM_KEY_MISMATCH',
    NOT_FOUND: 'NOT_FOUND',
    INVALID_ID: 'INVALID_ID',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    ERP_PROXY_FAILED: 'ERP_PROXY_FAILED',
};

function createApiSuccessResponse(data, message) {
    return {
        success: true,
        data,
        ...(message ? { message } : {}),
    };
}

function createApiErrorResponse(code, extras = {}) {
    return {
        error: code,
        ...extras,
    };
}

module.exports = {
    API_ERROR_CODES,
    createApiSuccessResponse,
    createApiErrorResponse,
};
