import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'

const ROOT = process.cwd();

function read(filePath: string): string {
  return fs.readFileSync(`${ROOT}/${filePath}`, 'utf8');
}

test('inventory view guard: shows inventory receipts section with order filter support', () => {
  const view = read('src/views/Inventory.vue');
  const store = read('src/stores/useInventoryStore.ts');
  const pageState = read('src/features/inventory/composables/useInventoryPageState.ts');
  const pageQueryState = read('src/features/inventory/composables/useInventoryPageQueryState.ts');
  const movementDetailState = read('src/features/inventory/composables/useInventoryMovementDetailState.ts');
  const pageListState = read('src/features/inventory/composables/useInventoryPageListState.ts');
  const outboundState = read('src/features/inventory/composables/useInventoryOutboundState.ts');
  const outboundQueryState = read('src/features/inventory/composables/useInventoryOutboundQueryState.ts');
  const outboundReverseState = read('src/features/inventory/composables/useInventoryOutboundReverseState.ts');
  const outboundDetailState = read('src/features/inventory/composables/useInventoryOutboundDetailState.ts');
  const outboundSubmitState = read('src/features/inventory/composables/useInventoryOutboundSubmitState.ts');
  const outboundListState = read('src/features/inventory/composables/useInventoryOutboundListState.ts');
  const locationQueryState = read('src/features/inventory/composables/useInventoryLocationQueryState.ts');
  const locationDialogState = read('src/features/inventory/composables/useInventoryLocationDialogState.ts');
  const stockTab = read('src/features/inventory/components/InventoryStockTab.vue');
  const receiptsTab = read('src/features/inventory/components/InventoryReceiptsTab.vue');
  const outboundsTab = read('src/features/inventory/components/InventoryOutboundsTab.vue');
  const locationsTab = read('src/features/inventory/components/InventoryLocationsTab.vue');
  const receiptAuditState = read('src/features/inventory/composables/useInventoryReceiptAuditState.ts');
  const receiptReverseState = read('src/features/inventory/composables/useInventoryReceiptReverseState.ts');
  const routeState = read('src/features/inventory/composables/useInventoryReceiptRouteState.ts');
  const columns = read('src/components/inventory/InventoryReceiptColumns.ts');
  const locationDialog = read('src/components/inventory/InventoryLocationDialog.vue');
  const outboundDialog = read('src/components/inventory/InventoryOutboundDialog.vue');
  const router = read('src/router/index.ts');
  const detailView = read('src/views/InventoryReceiptDetail.vue');
  const queryBuilders = read('src/features/inventory/inventoryQueryBuilders.ts');
  const csvExports = read('src/features/inventory/inventoryCsvExports.ts');
  const storePaging = read('src/features/inventory/inventoryStorePaging.ts');
  const storeFlows = read('src/features/inventory/inventoryStoreFlows.ts');
  const storeHistoryFlows = read('src/features/inventory/inventoryStoreHistoryFlows.ts');
  const storeHistoryActions = read('src/features/inventory/inventoryStoreHistoryActions.ts');
  const storeCoreActions = read('src/features/inventory/inventoryStoreCoreActions.ts');
  const storeFlowActions = read('src/features/inventory/inventoryStoreFlowActions.ts');
  const storeStatefulActions = read('src/features/inventory/inventoryStoreStatefulActions.ts');
  const storeActions = read('src/features/inventory/inventoryStoreActions.ts');
  const storeExportActions = read('src/features/inventory/inventoryStoreExportActions.ts');
  const storeState = read('src/features/inventory/inventoryStoreState.ts');
  const storeDerivedState = read('src/features/inventory/inventoryStoreDerivedState.ts');
  const storeMetaState = read('src/features/inventory/inventoryStoreMetaState.ts');
  const storeCollections = read('src/features/inventory/inventoryStoreCollections.ts');

  assert.match(view, /采购入库记录/);
  assert.match(view, /正式出库记录/);
  assert.match(view, /库位管理/);
  assert.match(view, /InventoryOutboundDialog/);
  assert.match(view, /InventoryLocationDialog/);
  assert.match(view, /InventoryStockTab/);
  assert.match(view, /InventoryReceiptsTab/);
  assert.match(view, /InventoryOutboundsTab/);
  assert.match(view, /InventoryLocationsTab/);
  assert.match(view, /selectedInventoryRows/);
  assert.match(view, /selectedMovementItem/);
  assert.match(view, /outboundDialogOpen/);
  assert.match(view, /locationDialogOpen/);
  assert.match(view, /reconciliationOnly/);
  assert.match(view, /reconciliationSummary/);
  assert.match(view, /fetchInventoryLocations/);
  assert.match(view, /useInventoryPageState/);
  assert.match(view, /useInventoryOutboundState/);
  assert.doesNotMatch(view, /useInventoryLocationState/);
  assert.doesNotMatch(view, /useInventoryDetailPanels/);
  assert.doesNotMatch(view, /const reverseReceiptDialogOpen =/);
  assert.doesNotMatch(view, /const reverseOutboundConfirmOpen =/);
  assert.doesNotMatch(view, /const closeReceiptAuditPanel =/);
  assert.doesNotMatch(view, /useInventoryReverseDialogs/);
  assert.match(view, /库存影响轨迹/);
  assert.match(view, /确认冲销/);
  assert.match(view, /receiptSearchQuery/);
  assert.match(view, /receiptOrderFilter/);
  assert.match(view, /receiptDirectionFilter/);
  assert.match(view, /reverseReasonFilter/);
  assert.match(view, /receiptPage/);
  assert.match(view, /receiptPageSize/);
  assert.match(view, /receiptSummary/);
  assert.match(view, /receiptTotalPages/);
  assert.match(view, /availableReverseReasonOptions/);
  assert.match(view, /handleExportReceipts/);
  assert.match(view, /handleExportInventory/);
  assert.match(view, /handleExportReconciliation/);
  assert.match(view, /handleExportOutbounds/);
  assert.match(view, /handleContextExport/);
  assert.match(view, /currentExportLabel/);
  assert.match(view, /fetchAllInventoryReceipts/);
  assert.match(view, /useInventoryReceiptRouteState/);
  assert.doesNotMatch(view, /useInventoryReceiptFlow/);
  assert.match(view, /buildReceiptFetchParams/);
  assert.match(view, /clearReceiptRouteFilters/);
  assert.match(view, /fetchInventoryReceipts/);
  assert.match(view, /exportReceiptsToCSV/);
  assert.match(view, /loadReceipts/);
  assert.match(view, /入库记录加载失败/);
  assert.match(view, /route\.query\.orderNo/);
  assert.match(view, /route\.query\.tab/);
  assert.match(view, /导出库位余额/);
  assert.match(view, /isReceiptReversible/);
  assert.match(view, /selectedReceiptAudit/);
  assert.match(view, /openReceiptAudit/);
  assert.match(view, /closeReceiptAudit/);
  assert.match(view, /inventory-receipt-detail/);
  assert.match(view, /SheetContent/);
  assert.match(view, /SheetTitle/);
  assert.match(view, /SheetDescription/);
  assert.match(view, /PROCUREMENT_REFRESH_SIGNAL_KEY/);
  assert.match(view, /window\.localStorage\.setItem/);
  assert.match(view, /ConfirmDialog/);
  assert.match(view, /确认撤销入库/);
  assert.match(view, /reverseReasonOptions/);
  assert.match(view, /reverseReason/);
  assert.match(view, /reverseRemark/);
  assert.match(view, /reverseQuantity/);
  assert.match(view, /剩余可撤销/);
  assert.match(view, /本次撤销数量/);
  assert.match(view, /全部撤销/);
  assert.match(view, /入库撤销轨迹/);
  assert.match(view, /当前仅展示最近 \{\{ store\.movementsPageSize \}\} 条轨迹/);
  assert.match(view, /净入库数量/);
  assert.match(view, /尚无撤销流水/);
  assert.match(view, /跳转采购单/);
  assert.match(view, /nextReceiptPage/);
  assert.match(view, /prevReceiptPage/);
  assert.match(pageState, /useInventoryPageQueryState/);
  assert.match(pageState, /useInventoryPageListState/);
  assert.match(pageListState, /export function useInventoryPageListState/);
  assert.match(pageListState, /async function loadInventoryList/);
  assert.match(pageListState, /function handleExportInventory/);
  assert.match(pageListState, /function handleExportReconciliation/);
  assert.match(pageState, /useInventoryMovementDetailState/);
  assert.match(movementDetailState, /export function useInventoryMovementDetailState/);
  assert.match(movementDetailState, /const selectedMovementItem = ref/);
  assert.match(movementDetailState, /const selectedMovementSummary = computed/);
  assert.match(movementDetailState, /function formatMovementSourceLabel/);
  assert.match(movementDetailState, /async function openMovementSheet/);
  assert.match(movementDetailState, /function closeMovementSheet/);
  assert.match(pageQueryState, /export function useInventoryPageQueryState/);
  assert.match(pageQueryState, /const activeCategory = ref/);
  assert.match(pageQueryState, /const debouncedSearchQuery = refDebounced/);
  assert.match(pageQueryState, /const availableInventoryLocations = computed/);
  assert.match(pageQueryState, /const filteredItems = computed/);
  assert.match(pageQueryState, /const reconciliationSummary = computed/);
  assert.match(pageQueryState, /const reconciliationOnly = ref/);
  assert.match(movementDetailState, /const selectedMovementItem = ref/);
  assert.match(pageListState, /async function loadInventoryList/);
  assert.match(movementDetailState, /async function openMovementSheet/);
  assert.match(pageState, /fetchInventoryMovements/);
  assert.match(pageListState, /function handleExportInventory/);
  assert.match(pageListState, /function handleExportReconciliation/);
  assert.match(pageQueryState, /selectedWarehouseFilter/);
  assert.match(pageQueryState, /selectedLocationFilter/);
  assert.match(stockTab, /总物料数/);
  assert.match(stockTab, /低水位预警/);
  assert.match(stockTab, /启用库位/);
  assert.match(stockTab, /已选出库物料/);
  assert.match(stockTab, /对账异常物料/);
  assert.match(stockTab, /累计差异量/);
  assert.match(stockTab, /仅看对账异常/);
  assert.match(stockTab, /导出对账异常/);
  assert.match(stockTab, /出库登记/);
  assert.match(outboundSubmitState, /const outboundDialogOpen = ref/);
  assert.match(outboundState, /useInventoryOutboundReverseState/);
  assert.match(outboundState, /useInventoryOutboundDetailState/);
  assert.match(outboundState, /useInventoryOutboundSubmitState/);
  assert.match(outboundState, /useInventoryOutboundListState/);
  assert.match(outboundListState, /export function useInventoryOutboundListState/);
  assert.match(outboundListState, /fetchInventoryOutbounds/);
  assert.match(outboundListState, /fetchAllInventoryOutbounds/);
  assert.match(outboundListState, /async function loadOutbounds/);
  assert.match(outboundListState, /function handleExportOutbounds/);
  assert.match(outboundListState, /function nextOutboundPage/);
  assert.match(outboundListState, /function prevOutboundPage/);
  assert.match(outboundSubmitState, /export function useInventoryOutboundSubmitState/);
  assert.match(outboundSubmitState, /createInventoryOutbound/);
  assert.match(outboundSubmitState, /const outboundDialogOpen = ref/);
  assert.match(outboundSubmitState, /const outboundSaving = ref/);
  assert.match(outboundSubmitState, /function openOutboundDialog/);
  assert.match(outboundSubmitState, /async function handleSubmitOutbound/);
  assert.match(outboundDetailState, /export function useInventoryOutboundDetailState/);
  assert.match(outboundDetailState, /const selectedOutboundDetail = ref/);
  assert.match(outboundDetailState, /async function openOutboundDetail/);
  assert.match(outboundDetailState, /function closeOutboundDetail/);
  assert.match(outboundSubmitState, /function openOutboundDialog/);
  assert.match(outboundSubmitState, /InventoryOutboundPayload/);
  assert.match(outboundSubmitState, /async function handleSubmitOutbound/);
  assert.match(outboundState, /useInventoryOutboundReverseState/);
  assert.match(outboundReverseState, /export function useInventoryOutboundReverseState/);
  assert.match(outboundReverseState, /reverseInventoryOutbound/);
  assert.match(outboundReverseState, /export type InventoryOutboundReverseControls/);
  assert.match(outboundReverseState, /function requestReverseOutbound/);
  assert.match(outboundReverseState, /async function confirmReverseOutbound/);
  assert.match(outboundState, /useInventoryOutboundQueryState/);
  assert.match(outboundQueryState, /export function useInventoryOutboundQueryState/);
  assert.match(outboundQueryState, /const outboundNoFilter = ref/);
  assert.match(outboundQueryState, /const availableOutboundLocations = computed/);
  assert.match(outboundQueryState, /const outboundSummary = computed/);
  assert.match(outboundQueryState, /const outboundTotalPages = computed/);
  assert.match(outboundReverseState, /async function confirmReverseOutbound/);
  assert.match(outboundDetailState, /async function openOutboundDetail/);
  assert.match(outboundDetailState, /function closeOutboundDetail/);
  assert.match(receiptReverseState, /function resetReceiptReverseQuantityToMax/);
  assert.match(outboundDialog, /InventoryOutboundPayload/);
  assert.match(outboundsTab, /出库单数/);
  assert.match(outboundsTab, /涉及库位/);
  assert.match(outboundsTab, /累计出库/);
  assert.match(outboundsTab, /净出库/);
  assert.match(outboundsTab, /暂无正式出库记录/);
  assert.match(outboundsTab, /清空筛选/);
  assert.match(outboundsTab, /上一页/);
  assert.match(outboundsTab, /下一页/);
  assert.match(locationDialogState, /export function useInventoryLocationDialogState/);
  assert.match(locationDialogState, /const locationDialogOpen = ref/);
  assert.match(locationDialogState, /const locationDialogSaving = ref/);
  assert.match(locationDialogState, /const editingLocation = ref/);
  assert.match(locationDialogState, /async function handleLocationSubmit/);
  assert.match(locationDialogState, /function openCreateLocationDialog/);
  assert.match(locationDialogState, /function openEditLocationDialog/);
  assert.match(locationQueryState, /export function useInventoryLocationQueryState/);
  assert.match(locationQueryState, /const locationSearchQuery = ref/);
  assert.match(locationQueryState, /const filteredLocations = computed/);
  assert.match(locationDialogState, /InventoryLocationPayload/);
  assert.match(locationDialog, /InventoryLocationPayload/);
  assert.match(locationDialogState, /async function handleLocationSubmit/);
  assert.match(locationDialogState, /fetchInventoryLocations/);
  assert.match(locationDialogState, /function openCreateLocationDialog/);
  assert.match(locationsTab, /仓库数/);
  assert.match(locationsTab, /全部库位/);
  assert.match(locationsTab, /启用库位/);
  assert.match(locationsTab, /新建库位/);
  assert.match(locationsTab, /暂无库位配置/);
  assert.match(receiptsTab, /记录总数/);
  assert.match(receiptsTab, /当前筛选记录数/);
  assert.match(receiptsTab, /涉及订单数/);
  assert.match(receiptsTab, /累计入库/);
  assert.match(receiptsTab, /总计入库数量/);
  assert.match(receiptsTab, /净入库/);
  assert.match(receiptsTab, /最近入库/);
  assert.match(receiptsTab, /当前按采购订单/);
  assert.match(receiptsTab, /20 \/ 页/);
  assert.match(receiptsTab, /50 \/ 页/);
  assert.match(receiptsTab, /100 \/ 页/);
  assert.match(receiptsTab, /暂无采购入库记录/);
  assert.match(view, /useInventoryReceiptAuditState/);
  assert.match(view, /useInventoryReceiptReverseState/);
  assert.match(receiptAuditState, /export type InventoryReceiptAuditState/);
  assert.match(receiptReverseState, /export function useInventoryReceiptReverseState/);
  assert.match(receiptReverseState, /export type InventoryReceiptReverseControls/);
  assert.match(receiptReverseState, /function requestReverseReceipt/);
  assert.match(receiptReverseState, /async function confirmReverseReceipt/);
  assert.match(receiptAuditState, /export function useInventoryReceiptAuditState/);
  assert.match(receiptAuditState, /const auditReceiptId = ref/);
  assert.match(receiptAuditState, /const selectedReceiptAudit = computed/);
  assert.match(receiptAuditState, /async function openReceiptAudit/);
  assert.match(receiptReverseState, /export type InventoryReceiptReverseControls/);
  assert.match(receiptReverseState, /function resetReceiptReverseQuantityToMax/);
  assert.match(receiptReverseState, /reverseReceipt:/);
  assert.match(receiptReverseState, /撤销成功/);
  assert.match(receiptReverseState, /撤销失败/);
  assert.match(routeState, /refDebounced/);
  assert.match(routeState, /debouncedReceiptSearchQuery/);
  assert.match(routeState, /route\.query\.keyword/);
  assert.match(routeState, /route\.query\.direction/);
  assert.match(routeState, /route\.query\.reverseReason/);
  assert.match(routeState, /route\.query\.page/);
  assert.match(routeState, /route\.query\.pageSize/);
  assert.match(routeState, /route\.query\.tab/);
  assert.match(routeState, /updateInventoryReceiptRouteQuery/);
  assert.match(routeState, /clearReceiptRouteFilters/);
  assert.match(routeState, /buildReceiptFetchParams/);
  assert.match(store, /createInventoryStoreState/);
  assert.match(store, /createInventoryStoreActions/);
  assert.match(store, /\.\.\.state/);
  assert.match(store, /\.\.\.actions/);
  assert.match(storeState, /export type InventoryStoreState = ReturnType<typeof createInventoryStoreState>/);
  assert.match(storeState, /createInventoryCollections/);
  assert.match(storeState, /createInventoryMetaState/);
  assert.match(storeState, /createInventoryDerivedState/);
  assert.match(storeState, /\.\.\.collections/);
  assert.match(storeState, /\.\.\.metaState/);
  assert.match(storeState, /\.\.\.derivedState/);
  assert.match(storeDerivedState, /export function createInventoryDerivedState/);
  assert.match(storeDerivedState, /const sortedReceipts = computed/);
  assert.match(storeDerivedState, /const sortedOutbounds = computed/);
  assert.match(storeDerivedState, /const sortedMovements = computed/);
  assert.match(storeDerivedState, /const sortedItems = computed/);
  assert.match(storeDerivedState, /const lowStockItems = computed/);
  assert.match(storeDerivedState, /const activeLocations = computed/);
  assert.match(storeCollections, /export function createInventoryCollections/);
  assert.match(storeCollections, /const items = ref/);
  assert.match(storeCollections, /const receipts = ref/);
  assert.match(storeCollections, /const warehouses = ref/);
  assert.match(storeCollections, /const locations = ref/);
  assert.match(storeCollections, /const outbounds = ref/);
  assert.match(storeCollections, /const movements = ref/);
  assert.match(storeMetaState, /export function createInventoryMetaState/);
  assert.match(storeMetaState, /const loading = ref/);
  assert.match(storeMetaState, /const receiptsTotal = ref/);
  assert.match(storeMetaState, /const receiptsPage = ref/);
  assert.match(storeMetaState, /const receiptsPageSize = ref/);
  assert.match(storeMetaState, /const movementsTotal = ref/);
  assert.match(storeMetaState, /const movementsPage = ref/);
  assert.match(storeMetaState, /const movementsPageSize = ref/);
  assert.match(storeActions, /export function createInventoryStoreActions/);
  assert.match(storeActions, /InventoryStoreState/);
  assert.doesNotMatch(storeActions, /createInventoryStoreState/);
  assert.match(storeActions, /createInventoryStatefulActions/);
  assert.match(storeActions, /createInventoryExportActions/);
  assert.match(storeActions, /\.\.\.statefulActions/);
  assert.match(storeActions, /\.\.\.exportActions/);
  assert.match(storeStatefulActions, /InventoryStoreState/);
  assert.doesNotMatch(storeStatefulActions, /inventoryStoreActions/);
  assert.match(storeStatefulActions, /export function createInventoryStatefulActions/);
  assert.match(storeStatefulActions, /createInventoryCoreActions/);
  assert.match(storeStatefulActions, /createInventoryHistoryActions/);
  assert.match(storeStatefulActions, /createInventoryFlowActions/);
  assert.match(storeExportActions, /export function createInventoryExportActions/);
  assert.match(storeExportActions, /exportReceiptsToCSV/);
  assert.match(storeExportActions, /exportInventoryToCSV/);
  assert.match(storeExportActions, /exportReconciliationToCSV/);
  assert.match(storeExportActions, /exportOutboundsToCSV/);
  assert.match(storeCoreActions, /export function createInventoryCoreActions/);
  assert.match(storeCoreActions, /async function fetchInventory/);
  assert.match(storeCoreActions, /async function updateMinStock/);
  assert.match(storeCoreActions, /async function createInventoryAdjustment/);
  assert.match(storeCoreActions, /fetchInventoryFlow/);
  assert.match(storeCoreActions, /updateInventoryMinStockFlow/);
  assert.match(storeCoreActions, /createInventoryAdjustmentFlow/);
  assert.match(storeFlowActions, /InventoryLocationPayload/);
  assert.match(storeFlowActions, /InventoryOutboundPayload/);
  assert.match(storeFlowActions, /InventoryOutboundReversePayload/);
  assert.match(storeFlowActions, /inventoryStoreFlows/);
  assert.doesNotMatch(storeFlowActions, /export type InventoryOutboundPayload/);
  assert.match(storeFlowActions, /export function createInventoryFlowActions/);
  assert.match(storeFlowActions, /async function fetchInventoryLocations/);
  assert.match(storeFlowActions, /async function createInventoryLocation/);
  assert.doesNotMatch(storeFlowActions, /warehouse_id: number;\n    code: string;/);
  assert.match(storeFlowActions, /async function updateInventoryLocation/);
  assert.match(storeFlowActions, /async function fetchInventoryOutbounds/);
  assert.match(storeFlowActions, /async function fetchInventoryOutbound/);
  assert.match(storeFlowActions, /async function fetchAllInventoryOutbounds/);
  assert.match(storeFlowActions, /async function createInventoryOutbound/);
  assert.match(storeFlowActions, /async function reverseInventoryOutbound/);
  assert.match(storeFlowActions, /fetchInventoryLocationsFlow/);
  assert.match(storeFlowActions, /fetchInventoryOutboundsFlow/);
  assert.match(storeFlowActions, /reverseInventoryOutboundFlow/);
  assert.match(locationDialog, /warehouseLocked/);
  assert.match(locationDialog, /:disabled="warehouseLocked"/);
  assert.match(locationDialog, /已建库位不允许更换所属仓库/);
  assert.match(storeHistoryActions, /InventoryReceiptReversePayload/);
  assert.match(storeHistoryActions, /fetchInventoryReceiptsFlow/);
  assert.match(storeHistoryActions, /fetchAllInventoryReceiptsFlow/);
  assert.match(storeHistoryActions, /fetchInventoryMovementsFlow/);
  assert.match(storeStatefulActions, /\.\.\.flowActions/);
  assert.match(storePaging, /export type PagedRowsResponse/);
  assert.match(storePaging, /export function normalizePagedRowsResponse/);
  assert.match(storePaging, /export async function fetchAllPagedRows/);
  assert.match(storePaging, /const pageSize = options\.pageSize \?\? 200/);
  assert.match(storeFlows, /export type InventoryLocationPayload/);
  assert.match(storeFlows, /export type InventoryOutboundPayload/);
  assert.match(storeFlows, /export type InventoryOutboundReversePayload/);
  assert.match(storeFlows, /export async function fetchInventoryLocationsFlow/);
  assert.match(storeFlows, /export async function fetchInventoryOutboundsFlow/);
  assert.match(storeFlows, /export async function fetchAllInventoryOutboundsFlow/);
  assert.match(storeHistoryFlows, /export type InventoryReceiptReversePayload/);
  assert.match(storeHistoryFlows, /export async function fetchInventoryReceiptsFlow/);
  assert.match(storeHistoryFlows, /export async function fetchAllInventoryReceiptsFlow/);
  assert.match(storeHistoryFlows, /export async function fetchInventoryMovementsFlow/);
  assert.match(storeHistoryActions, /export function createInventoryHistoryActions/);
  assert.match(storeHistoryActions, /async function fetchInventoryReceipts/);
  assert.match(storeHistoryActions, /async function fetchAllInventoryReceipts/);
  assert.match(storeHistoryActions, /async function fetchInventoryReceipt/);
  assert.match(storeHistoryActions, /async function reverseReceipt/);
  assert.match(storeHistoryActions, /async function fetchInventoryMovements/);
  assert.match(queryBuilders, /function appendIfPresent/);
  assert.match(queryBuilders, /appendIfPresent\(query, 'keyword'/);
  assert.match(queryBuilders, /appendIfPresent\(query, 'direction'/);
  assert.match(queryBuilders, /appendIfPresent\(query, 'reverseReason'/);
  assert.match(storeHistoryActions, /async function reverseReceipt/);
  assert.match(csvExports, /function exportReceiptsToCSV/);
  assert.match(csvExports, /function exportInventoryToCSV/);
  assert.match(csvExports, /function exportReconciliationToCSV/);
  assert.match(csvExports, /function exportOutboundsToCSV/);
  assert.match(csvExports, /方向/);
  assert.match(csvExports, /剩余可撤销/);
  assert.match(storeHistoryActions, /receipts\.value = \[\]/);
  assert.match(columns, /header:\s*'入库日期'/);
  assert.match(columns, /header:\s*'订单号'/);
  assert.match(read('src/components/inventory/InventoryColumns.ts'), /header:\s*'库位汇总'/);
  assert.match(read('src/components/inventory/InventoryColumns.ts'), /header:\s*'对账差异'/);
  assert.match(columns, /header:\s*'库位'/);
  assert.match(columns, /header:\s*'方向'/);
  assert.match(columns, /header:\s*'操作人'/);
  assert.match(columns, /header:\s*'撤销原因'/);
  assert.match(columns, /header:\s*'剩余可撤销'/);
  assert.match(columns, /轨迹/);
  assert.match(columns, /详情/);
  assert.match(columns, /撤销/);
  assert.match(router, /name:\s*'inventory-receipt-detail'/);
  assert.match(detailView, /入库记录详情/);
  assert.match(detailView, /loadDetail/);
  assert.match(detailView, /fetchInventoryReceipt/);
  assert.match(detailView, /跳转采购单/);
  assert.match(detailView, /watch\(\(\) => route\.params\.id/);
  assert.match(detailView, /query: \{ tab: 'receipts' \}/);
});
