import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'

const ROOT = process.cwd();

function read(filePath: string): string {
  return fs.readFileSync(`${ROOT}/${filePath}`, 'utf8');
}

test('inventory view guard: shows inventory receipts section with order filter support', () => {
  const view = read('src/views/Inventory.vue');
  const store = read('src/stores/useInventoryStore.ts');
  const receiptFlow = read('src/features/inventory/composables/useInventoryReceiptFlow.ts');
  const routeState = read('src/features/inventory/composables/useInventoryReceiptRouteState.ts');
  const columns = read('src/components/inventory/InventoryReceiptColumns.ts');
  const router = read('src/router/index.ts');
  const detailView = read('src/views/InventoryReceiptDetail.vue');

  assert.match(view, /采购入库记录/);
  assert.match(view, /receiptSearchQuery/);
  assert.match(view, /receiptOrderFilter/);
  assert.match(view, /receiptDirectionFilter/);
  assert.match(view, /reverseReasonFilter/);
  assert.match(view, /receiptPage/);
  assert.match(view, /receiptPageSize/);
  assert.match(view, /receiptSummary/);
  assert.match(view, /receiptTotalPages/);
  assert.match(view, /availableReverseReasonOptions/);
  assert.match(view, /handleExportReceipts/);
  assert.match(view, /fetchAllInventoryReceipts/);
  assert.match(view, /useInventoryReceiptRouteState/);
  assert.match(view, /useInventoryReceiptFlow/);
  assert.match(view, /buildReceiptFetchParams/);
  assert.match(view, /clearReceiptRouteFilters/);
  assert.match(view, /fetchInventoryReceipts/);
  assert.match(view, /exportReceiptsToCSV/);
  assert.match(view, /loadReceipts/);
  assert.match(view, /入库记录加载失败/);
  assert.match(view, /累计入库/);
  assert.match(view, /净入库/);
  assert.match(view, /涉及订单数/);
  assert.match(view, /当前筛选记录数/);
  assert.match(view, /总计入库数量/);
  assert.match(view, /route\.query\.orderNo/);
  assert.match(view, /route\.query\.tab/);
  assert.match(view, /当前按采购订单/);
  assert.match(view, /全部方向/);
  assert.match(view, /仅入库/);
  assert.match(view, /仅撤销/);
  assert.match(view, /全部原因/);
  assert.match(view, /isReceiptReversible/);
  assert.match(view, /selectedReceiptAudit/);
  assert.match(view, /openReceiptAudit/);
  assert.match(view, /closeReceiptAudit/);
  assert.match(view, /inventory-receipt-detail/);
  assert.match(view, /SheetContent/);
  assert.match(view, /SheetTitle/);
  assert.match(view, /SheetDescription/);
  assert.match(view, /PROCUREMENT_REFRESH_SIGNAL_KEY/);
  assert.match(view, /window\.localStorage\.setItem/);
  assert.match(view, /ConfirmDialog/);
  assert.match(view, /确认撤销入库/);
  assert.match(view, /reverseReasonOptions/);
  assert.match(view, /reverseReason/);
  assert.match(view, /reverseRemark/);
  assert.match(view, /reverseQuantity/);
  assert.match(view, /剩余可撤销/);
  assert.match(view, /本次撤销数量/);
  assert.match(view, /全部撤销/);
  assert.match(view, /入库撤销轨迹/);
  assert.match(view, /净入库数量/);
  assert.match(view, /尚无撤销流水/);
  assert.match(view, /跳转采购单/);
  assert.match(view, /nextReceiptPage/);
  assert.match(view, /prevReceiptPage/);
  assert.match(view, /共 \{\{ store\.receiptsTotal \}\} 条/);
  assert.match(view, /20 \/ 页/);
  assert.match(view, /50 \/ 页/);
  assert.match(view, /100 \/ 页/);
  assert.match(receiptFlow, /requestReverseReceipt/);
  assert.match(receiptFlow, /confirmReverseReceipt/);
  assert.match(receiptFlow, /openReceiptAudit/);
  assert.match(receiptFlow, /closeReceiptAudit/);
  assert.match(receiptFlow, /selectedReceiptAudit/);
  assert.match(receiptFlow, /auditReceiptId/);
  assert.match(receiptFlow, /auditRows/);
  assert.match(receiptFlow, /notifyProcurementRefresh/);
  assert.match(receiptFlow, /store\.reverseReceipt/);
  assert.match(receiptFlow, /撤销成功/);
  assert.match(receiptFlow, /撤销失败/);
  assert.match(routeState, /refDebounced/);
  assert.match(routeState, /debouncedReceiptSearchQuery/);
  assert.match(routeState, /route\.query\.keyword/);
  assert.match(routeState, /route\.query\.direction/);
  assert.match(routeState, /route\.query\.reverseReason/);
  assert.match(routeState, /route\.query\.page/);
  assert.match(routeState, /route\.query\.pageSize/);
  assert.match(routeState, /route\.query\.tab/);
  assert.match(routeState, /updateInventoryReceiptRouteQuery/);
  assert.match(routeState, /clearReceiptRouteFilters/);
  assert.match(routeState, /buildReceiptFetchParams/);
  assert.match(store, /const receipts = ref/);
  assert.match(store, /const sortedReceipts = computed/);
  assert.match(store, /const receiptsTotal = ref/);
  assert.match(store, /const receiptsPage = ref/);
  assert.match(store, /const receiptsPageSize = ref/);
  assert.match(store, /async function fetchInventoryReceipts/);
  assert.match(store, /async function fetchAllInventoryReceipts/);
  assert.match(store, /async function fetchInventoryReceipt/);
  assert.match(store, /const pageSize = 200/);
  assert.match(store, /query\.set\('keyword'/);
  assert.match(store, /query\.set\('direction'/);
  assert.match(store, /query\.set\('reverseReason'/);
  assert.match(store, /async function reverseReceipt/);
  assert.match(store, /function exportReceiptsToCSV/);
  assert.match(store, /方向/);
  assert.match(store, /剩余可撤销/);
  assert.match(store, /receipts\.value = \[\]/);
  assert.match(columns, /header:\s*'入库日期'/);
  assert.match(columns, /header:\s*'订单号'/);
  assert.match(columns, /header:\s*'方向'/);
  assert.match(columns, /header:\s*'操作人'/);
  assert.match(columns, /header:\s*'撤销原因'/);
  assert.match(columns, /header:\s*'剩余可撤销'/);
  assert.match(columns, /轨迹/);
  assert.match(columns, /详情/);
  assert.match(columns, /撤销/);
  assert.match(router, /name:\s*'inventory-receipt-detail'/);
  assert.match(detailView, /入库记录详情/);
  assert.match(detailView, /loadDetail/);
  assert.match(detailView, /fetchInventoryReceipt/);
  assert.match(detailView, /跳转采购单/);
  assert.match(detailView, /watch\(\(\) => route\.params\.id/);
  assert.match(detailView, /query: \{ tab: 'receipts' \}/);
});
