import { API_ERROR_CODES } from '../../shared/contracts/api';

/**
 * 后端应用级错误代码
 * 包含基础 API 合约定义的错误码及各业务模块特定的错误码
 */
export const ERROR_CODES = {
    ...API_ERROR_CODES,
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    RECEIPT_NOT_FOUND: 'RECEIPT_NOT_FOUND',
    RECEIPT_REVERSE_NOT_ALLOWED: 'RECEIPT_REVERSE_NOT_ALLOWED',
    RECEIPT_ALREADY_REVERSED: 'RECEIPT_ALREADY_REVERSED',
    RECEIPT_ALREADY_FULLY_REVERSED: 'RECEIPT_ALREADY_FULLY_REVERSED',
    RECEIPT_REVERSE_CONFLICT: 'RECEIPT_REVERSE_CONFLICT',
    RECEIPT_INSUFFICIENT_BALANCE: 'RECEIPT_INSUFFICIENT_BALANCE',
    REVERSE_REASON_REQUIRED: 'REVERSE_REASON_REQUIRED',
    REVERSE_QUANTITY_EXCEEDED: 'REVERSE_QUANTITY_EXCEEDED',
    INVALID_RECEIPT_DATE: 'INVALID_RECEIPT_DATE',
    ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
    WAREHOUSE_NOT_FOUND: 'WAREHOUSE_NOT_FOUND',
    LOCATION_NOT_FOUND: 'LOCATION_NOT_FOUND',
    LOCATION_INACTIVE: 'LOCATION_INACTIVE',
    LOCATION_WAREHOUSE_MISMATCH: 'LOCATION_WAREHOUSE_MISMATCH',
    LOCATION_WAREHOUSE_IMMUTABLE: 'LOCATION_WAREHOUSE_IMMUTABLE',
    OUTBOUND_NOT_FOUND: 'OUTBOUND_NOT_FOUND',
    OUTBOUND_ALREADY_REVERSED: 'OUTBOUND_ALREADY_REVERSED',
    OUTBOUND_INSUFFICIENT_BALANCE: 'OUTBOUND_INSUFFICIENT_BALANCE',
    OUTBOUND_ITEMS_REQUIRED: 'OUTBOUND_ITEMS_REQUIRED',
    OUTBOUND_REASON_REQUIRED: 'OUTBOUND_REASON_REQUIRED',
    INVENTORY_BALANCE_NEGATIVE: 'INVENTORY_BALANCE_NEGATIVE',
    STOCK_QUANTITY_IMMUTABLE: 'STOCK_QUANTITY_IMMUTABLE',
} as const;

export default ERROR_CODES;
