const { API_ERROR_CODES } = require('../../shared/contracts/api');

module.exports = {
    ...API_ERROR_CODES,
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    RECEIPT_NOT_FOUND: 'RECEIPT_NOT_FOUND',
    RECEIPT_REVERSE_NOT_ALLOWED: 'RECEIPT_REVERSE_NOT_ALLOWED',
    RECEIPT_ALREADY_REVERSED: 'RECEIPT_ALREADY_REVERSED',
    RECEIPT_ALREADY_FULLY_REVERSED: 'RECEIPT_ALREADY_FULLY_REVERSED',
    REVERSE_REASON_REQUIRED: 'REVERSE_REASON_REQUIRED',
    REVERSE_QUANTITY_EXCEEDED: 'REVERSE_QUANTITY_EXCEEDED',
    INVALID_RECEIPT_DATE: 'INVALID_RECEIPT_DATE',
    ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
};
