export const PROCUREMENT_DOCUMENT_TITLE = '颐家工贸 (  总厂  ) 采购订单';
export const PROCUREMENT_DOCUMENT_PREVIEW_TITLE = `${PROCUREMENT_DOCUMENT_TITLE}预览`;
export const PROCUREMENT_DOCUMENT_VIEW_TITLE = `查看${PROCUREMENT_DOCUMENT_TITLE}`;
export const PROCUREMENT_DOCUMENT_EDIT_TITLE = `编辑${PROCUREMENT_DOCUMENT_TITLE}`;
export const PROCUREMENT_DOCUMENT_CREATE_TITLE = `手动录入${PROCUREMENT_DOCUMENT_TITLE}`;
